name: todolist
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.17.5
  cupertino_icons: ^1.0.8
  uuid: ^4.3.1
  intl: ^0.18.1
  table_calendar: ^3.0.9   # ✅ Tambahkan ini
  fl_chart: ^0.66.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/0.png
    - images/1.png
    - images/2.png
    - images/3.png
    - images/4.png
    - images/7.png
    - images/banking.png
    - images/icon_edit.png
    - images/icon_time.png
