// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoX3nsxvu5qLTAj2CUgmU9jZbv8sHqvTw',
    appId: '1:842304360042:web:1107136fa5e8d2f2718413',
    messagingSenderId: '842304360042',
    projectId: 'todolist-7868f',
    authDomain: 'todolist-7868f.firebaseapp.com',
    storageBucket: 'todolist-7868f.firebasestorage.app',
    measurementId: 'G-148E5RHTC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG4LaY0C81gakrnQyS2Qv2rca_5OlywIU',
    appId: '1:842304360042:android:e5faa2b57ab66ea9718413',
    messagingSenderId: '842304360042',
    projectId: 'todolist-7868f',
    storageBucket: 'todolist-7868f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARBy8bIl6-JxvsFv087NZNFGciU8MRVPo',
    appId: '1:842304360042:ios:1d27cdd5e419007e718413',
    messagingSenderId: '842304360042',
    projectId: 'todolist-7868f',
    storageBucket: 'todolist-7868f.firebasestorage.app',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARBy8bIl6-JxvsFv087NZNFGciU8MRVPo',
    appId: '1:842304360042:ios:1d27cdd5e419007e718413',
    messagingSenderId: '842304360042',
    projectId: 'todolist-7868f',
    storageBucket: 'todolist-7868f.firebasestorage.app',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoX3nsxvu5qLTAj2CUgmU9jZbv8sHqvTw',
    appId: '1:842304360042:web:df2e4fe546266650718413',
    messagingSenderId: '842304360042',
    projectId: 'todolist-7868f',
    authDomain: 'todolist-7868f.firebaseapp.com',
    storageBucket: 'todolist-7868f.firebasestorage.app',
    measurementId: 'G-PVHDDCNH0B',
  );
}
